apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  labels:
    app: {{ .Release.Name }}
spec:
  ports:
  - name: {{ .Values.app.name }}
    port: {{ .Values.app.port }}
    protocol: {{ .Values.app.protocol }}
    targetPort: {{ .Values.app.port }}
  selector:
    app: {{ .Release.Name }}
  sessionAffinity: None
  type: ClusterIP
