token: your_bot_token
username: your_bot_username
hosting: github #you must choose `github` or `gitlab`
host: gitlab.com # it needs only if you choose gitlab in hosting
email: your_bot_username@example.com
changelog_begin: "BEGIN CHANGELOG" #if you will not add any key bot will use all description
changelog_end: "END CHANGELOG" #if you will not add any key bot will use all description
bearer_token: your_token
cliq: False
cliq_client_id: null
cliq_client_secret: null
cliq_refresh_token: null
cliq_channel_name: null 
